<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="1" total="8" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Selenium tests suite" duration-ms="43109" started-at="2016-07-25T11:33:25Z" finished-at="2016-07-25T11:34:09Z">
    <groups>
      <group name="login test">
        <method signature="MailTest.loginTest()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67]" name="loginTest" class="com.epam.tat.selenium.tests.MailTest"/>
      </group> <!-- login test -->
      <group name="save as draft">
        <method signature="MailTest.saveMail()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67]" name="saveMail" class="com.epam.tat.selenium.tests.MailTest"/>
      </group> <!-- save as draft -->
    </groups>
    <test name="E-Mail testing" duration-ms="43109" started-at="2016-07-25T11:33:25Z" finished-at="2016-07-25T11:34:09Z">
      <class name="com.epam.tat.selenium.tests.MailTest">
        <test-method status="PASS" signature="initStartPage(java.lang.String, java.lang.String)[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67]" name="initStartPage" is-config="true" duration-ms="5857" started-at="2016-07-25T14:33:25Z" finished-at="2016-07-25T14:33:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://mail.ru/]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mozilla]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initStartPage -->
        <test-method status="PASS" signature="initUsers()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67]" name="initUsers" is-config="true" duration-ms="1" started-at="2016-07-25T14:33:31Z" finished-at="2016-07-25T14:33:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initUsers -->
        <test-method status="PASS" signature="loginTest()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67]" name="loginTest" duration-ms="10069" started-at="2016-07-25T14:33:31Z" description="input login, password, press login button, check that login was successful" finished-at="2016-07-25T14:33:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="composeMailTest()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67]" name="composeMailTest" duration-ms="2786" depends-on-groups="login test" started-at="2016-07-25T14:33:41Z" description="compose email to be send to user2, subject and text fields should be generated automaticly" finished-at="2016-07-25T14:33:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- composeMailTest -->
        <test-method status="PASS" signature="saveMail()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67]" name="saveMail" duration-ms="172" started-at="2016-07-25T14:33:44Z" description="after composing email press &quot;save mail&quot; button" depends-on-methods="com.epam.tat.selenium.tests.MailTest.composeMailTest" finished-at="2016-07-25T14:33:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveMail -->
        <test-method status="FAIL" signature="checkDraftExists()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67]" name="checkDraftExists" duration-ms="15470" started-at="2016-07-25T14:33:44Z" description="go to draft folder and check that email presents there" depends-on-methods="com.epam.tat.selenium.tests.MailTest.saveMail" finished-at="2016-07-25T14:34:00Z">
          <exception class="org.openqa.selenium.StaleElementReferenceException">
            <message>
              <![CDATA[Element not found in the cache - perhaps the page has changed since it was looked up
Command duration or timeout: 15.19 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'EPBYMINW4514', ip: '10.6.176.34', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 9215cc9e-25a6-445b-9464-b06cdaadc205]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up
Command duration or timeout: 15.19 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'EPBYMINW4514', ip: '10.6.176.34', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 9215cc9e-25a6-445b-9464-b06cdaadc205
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:85)
	at com.epam.tat.selenium.tests.BasicTest.goToDraft(BasicTest.java:68)
	at com.epam.tat.selenium.tests.MailTest.checkDraft(MailTest.java:103)
	at com.epam.tat.selenium.tests.MailTest.checkDraftExists(MailTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'EPBYMINW4514', ip: '10.6.176.34', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_73'
Driver info: driver.version: unknown
	at <anonymous class>.fxdriver.cache.getElementAt(resource://fxdriver/modules/web-element-cache.js:9454)
	at <anonymous class>.Utils.getElementAt(file:///C:/Users/Katsiaryna_Pilnikava/AppData/Local/Temp/anonymous7868098661135240250webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:9039)
	at <anonymous class>.fxdriver.preconditions.visible(file:///C:/Users/Katsiaryna_Pilnikava/AppData/Local/Temp/anonymous7868098661135240250webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:10090)
	at <anonymous class>.DelayedCommand.prototype.checkPreconditions_(file:///C:/Users/Katsiaryna_Pilnikava/AppData/Local/Temp/anonymous7868098661135240250webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12644)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/Katsiaryna_Pilnikava/AppData/Local/Temp/anonymous7868098661135240250webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12661)
	at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///C:/Users/Katsiaryna_Pilnikava/AppData/Local/Temp/anonymous7868098661135240250webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:625)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.StaleElementReferenceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkDraftExists -->
        <test-method status="SKIP" signature="checkDraftContentTest()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67]" name="checkDraftContentTest" duration-ms="0" started-at="2016-07-25T14:34:00Z" description="open previously saved mail and check if content was saved properly" depends-on-methods="com.epam.tat.selenium.tests.MailTest.checkDraftExists" finished-at="2016-07-25T14:34:00Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MailTest.checkDraftContentTest()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MailTest.checkDraftContentTest()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkDraftContentTest -->
        <test-method status="SKIP" signature="sendEmail()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67]" name="sendEmail" duration-ms="0" started-at="2016-07-25T14:34:00Z" description="press &quot;send&quot; button to send the mail" depends-on-methods="com.epam.tat.selenium.tests.MailTest.checkDraftExists" finished-at="2016-07-25T14:34:00Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MailTest.sendEmail()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MailTest.sendEmail()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendEmail -->
        <test-method status="PASS" signature="clearEmailAndDisposeDriver()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67]" name="clearEmailAndDisposeDriver" is-config="true" duration-ms="8729" started-at="2016-07-25T14:34:00Z" finished-at="2016-07-25T14:34:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearEmailAndDisposeDriver -->
        <test-method status="SKIP" signature="checkThatEmailWasSend()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67]" name="checkThatEmailWasSend" duration-ms="0" started-at="2016-07-25T14:34:00Z" description="go to draft and make sure that email no longer presents at this folder" depends-on-methods="com.epam.tat.selenium.tests.MailTest.sendEmail" finished-at="2016-07-25T14:34:00Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MailTest.checkThatEmailWasSend()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MailTest.checkThatEmailWasSend()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkThatEmailWasSend -->
        <test-method status="SKIP" signature="checkEmailNotAtDrafts()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67]" name="checkEmailNotAtDrafts" duration-ms="0" started-at="2016-07-25T14:34:00Z" description="go to &quot;sent&quot; folder and check if message presents there" depends-on-methods="com.epam.tat.selenium.tests.MailTest.sendEmail" finished-at="2016-07-25T14:34:00Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MailTest.checkEmailNotAtDrafts()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MailTest.checkEmailNotAtDrafts()[pri:0, instance:com.epam.tat.selenium.tests.MailTest@6a024a67] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkEmailNotAtDrafts -->
      </class> <!-- com.epam.tat.selenium.tests.MailTest -->
    </test> <!-- E-Mail testing -->
  </suite> <!-- Selenium tests suite -->
</testng-results>
